### ISSUE TITLE
[Request] Incorporate the ERCF toolhead sensor port into the LGX mount.

### ISSUE THREAD

**Issue by devsfan1830** [MaximeLambrechts/Stealthburner-LGX-PCB#1]
Basically wonder if you would be able to make a version of your LGX mount based on the modification from this mount (https://github.com/EtteGit/EnragedRabbitProject/blob/main/usermods/LGX_Toolhead_Sensor/STL/LGX%20Front%20Mount.stl) to allow for the ERCF sensor to fit as well. If so this would be PERFECT for my intended eventual setup. As it stands now, I have the ERCF board and LGX based setup from the afterburner toolhead. But I intend to switch to stealth burner. Your mod as far as I know is the CLEANEST setup yet for a normal LGX based extruder. Even if I did go LGX lite, there doesn't appear to be ERCF support yet for that.

**Comment by MaximeLambrechts** [comment]
Hi ! 

I'll look into it. But I think it is very doable yes :) My PCB has the filament sensor connector and pinout exactly as on the original pcb from Hartk, so electrically it is already compatible.

**Comment by devsfan1830** [comment]
I dunno if its gonna work actually. I just made a rather crude brute force attempt to copy the cutout for the sensor into your mount model. It looks like the switch used for the ERCF sensor collides with the path of a screw used to mount to the LGX. Maybe that screw can be left unattached? I dont have an assembly to test myself.

![LGX Mod](https://user-images.githubusercontent.com/27990284/189496674-48f90cc3-80dc-4ebc-b994-a11bd42faaeb.jpg)
![model](https://user-images.githubusercontent.com/27990284/189496676-1f5e5e1d-4919-4f57-9c0b-c8835640047d.png)

**Comment by devsfan1830** [comment]
Actually, I think I used the wrong LGX mount for ERCF. I pulled that file from usermods. There appears to be a new standard mount using a different sensor setup: https://github.com/EtteGit/EnragedRabbitProject/blob/main/Filament_Sensor/Stls/LGX/LGX_on_AfterBurner_Adapter_ERCF_Sensor.stl

Ive also now just learned ERCF no longer uses a toolhead sensor? So maybe this is no longer necessary?

**Comment by devsfan1830** [comment]
Yeah ERCF has gone sensorless on the toolhead so no need to do this anymore.
